// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cmnws.web;

import fr.normandieuniv.cmnws.db.VNormandieLeocarte;
import fr.normandieuniv.cmnws.web.VNormandieLeocarteController;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect VNormandieLeocarteController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByAnneeUniversitaireEquals", "form" }, method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsForm(Model uiModel) {
        return "vnormandieleocarte/findVNormandieLeocartesByAnneeUniversitaireEquals";
    }
    
    @RequestMapping(params = "find=ByAnneeUniversitaireEquals", method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEquals(@RequestParam("anneeUniversitaire") String anneeUniversitaire, Model uiModel) {
        uiModel.addAttribute("vnormandieleocartes", VNormandieLeocarte.findVNormandieLeocartesByAnneeUniversitaireEquals(anneeUniversitaire).getResultList());
        return "vnormandieleocarte/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEquals", "form" }, method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsForm(Model uiModel) {
        return "vnormandieleocarte/findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEquals";
    }
    
    @RequestMapping(params = "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEquals", method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEquals(@RequestParam("anneeUniversitaire") String anneeUniversitaire, @RequestParam("codeBaseMetier") String codeBaseMetier, Model uiModel) {
        uiModel.addAttribute("vnormandieleocartes", VNormandieLeocarte.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEquals(anneeUniversitaire, codeBaseMetier).getResultList());
        return "vnormandieleocarte/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLike", "form" }, method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLikeForm(Model uiModel) {
        return "vnormandieleocarte/findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLike", method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLike(@RequestParam("anneeUniversitaire") String anneeUniversitaire, @RequestParam("codeBaseMetier") String codeBaseMetier, @RequestParam("nomSurCarte") String nomSurCarte, Model uiModel) {
        uiModel.addAttribute("vnormandieleocartes", VNormandieLeocarte.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsAndNomSurCarteLike(anneeUniversitaire, codeBaseMetier, nomSurCarte).getResultList());
        return "vnormandieleocarte/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLike", "form" }, method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLikeForm(Model uiModel) {
        return "vnormandieleocarte/findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLike", method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLike(@RequestParam("anneeUniversitaire") String anneeUniversitaire, @RequestParam("codeBaseMetier") String codeBaseMetier, @RequestParam("nomSurCarte") String nomSurCarte, Model uiModel) {
        uiModel.addAttribute("vnormandieleocartes", VNormandieLeocarte.findVNormandieLeocartesByAnneeUniversitaireEqualsAndCodeBaseMetierEqualsOrAnneeUniversitaireEqualsAndNomSurCarteLike(anneeUniversitaire, codeBaseMetier, nomSurCarte).getResultList());
        return "vnormandieleocarte/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUniversitaireEqualsAndNomSurCarteLike", "form" }, method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndNomSurCarteLikeForm(Model uiModel) {
        return "vnormandieleocarte/findVNormandieLeocartesByAnneeUniversitaireEqualsAndNomSurCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUniversitaireEqualsAndNomSurCarteLike", method = RequestMethod.GET)
    public String VNormandieLeocarteController.findVNormandieLeocartesByAnneeUniversitaireEqualsAndNomSurCarteLike(@RequestParam("anneeUniversitaire") String anneeUniversitaire, @RequestParam("nomSurCarte") String nomSurCarte, Model uiModel) {
        uiModel.addAttribute("vnormandieleocartes", VNormandieLeocarte.findVNormandieLeocartesByAnneeUniversitaireEqualsAndNomSurCarteLike(anneeUniversitaire, nomSurCarte).getResultList());
        return "vnormandieleocarte/list";
    }
    
}
