// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cmnws.db;

import fr.normandieuniv.cmnws.db.VNormandieLeocarte;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VNormandieLeocarte_Roo_Configurable {
    
    declare @type: VNormandieLeocarte: @Configurable;
    
}
